-- UNION
SELECT UNNEST([1,1,1,2])
UNION 
SELECT UNNEST([1,1,3]);

-- UNION ALL
SELECT UNNEST([1,1,1,2])
UNION ALL
SELECT UNNEST([1,1,3]);

-- INTERSECT
SELECT UNNEST([1,1,1,2])
INTERSECT
SELECT UNNEST([1,1,3]);

--- INTERSECT ALL
SELECT UNNEST([1,1,1,2])
INTERSECT ALL
SELECT UNNEST([1,1,3]);

--- EXCEPT 
SELECT UNNEST([1,1,1,2])
EXCEPT
SELECT UNNEST([1,1,3]);

--- EXCEPT ALL
SELECT UNNEST([1,1,1,2])
EXCEPT ALL
SELECT UNNEST([1,1,3]);

-----------------------------------------------
CREATE TEMP TABLE job_2023 AS
SELECT * EXCLUDE (job_id, job_posted_date)
FROM job_postings_fact
WHERE 
    EXTRACT(YEAR FROM job_posted_date) = 2023;

SELECT
    COUNT(*)
FROM job_2023;


CREATE TEMP TABLE job_2024 AS
SELECT * EXCLUDE (job_id, job_posted_date)
FROM job_postings_fact
WHERE 
    EXTRACT(YEAR FROM job_posted_date) = 2024;

SELECT
    COUNT(*)
FROM job_2024;


SELECT 'job_2023' AS table_name,
   COUNT(*)
FROM job_2023
UNION
SELECT 'job_2024' AS table_name,
   COUNT(*)
FROM job_2024;


SELECT 
    *
FROM job_2023
UNION ALL
SELECT 
    *
FROM job_2024;

-- WHICH JOB POSTINGS APPEARED IN 2023 BUT NOT IN 2024
SELECT *
FROM job_2023

EXCEPT

SELECT  *
FROM job_2024;

-- WHICH JOB POSTINGS APPEARED FROM 2023 REMAIN AFTER SUBTRACTING FROM THOSE THAT MATCH WITH 2024, ONE-FOR-ONE?
SELECT *
FROM job_2023

EXCEPT ALL

SELECT  *
FROM job_2024;

-- WHICH JOB POSTINGS APPEARED IN 2023 AND IN 2024

SELECT *
FROM job_2023

INTERSECT

SELECT  *
FROM job_2024;

-- WHICH JOB POSTINGS APPEARED IN both years, preserving duplicate counts?
SELECT *
FROM job_2023

INTERSECT ALL

SELECT  *
FROM job_2024;
